name: pricer
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.13
  - pip
  # Core ML and Data Processing (installed via conda)
  - pandas>=2.0.0
  - numpy>=1.24.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - scikit-learn>=1.3.0
  - scipy>=1.8.0
  - tqdm>=4.65.0
  - psutil>=5.9.0
  - requests>=2.31.0
  - httpx>=0.24.0

  # Jupyter and Development
  - jupyter>=1.0.0
  - ipykernel>=6.25.0
  - notebook>=6.5.0
  - ipython>=8.0.0

  # PyTorch and related packages
  - pytorch>=2.0.0
  - torchvision
  - torchaudio

  # HuggingFace packages
  - transformers>=4.30.0
  - datasets>=2.14.0
  - accelerate>=0.20.0

  # Additional packages via pip (for packages not available in conda)
  - pip:
      - openai>=1.0.0
      - anthropic>=0.7.0
      - google-generativeai>=0.3.0
      - huggingface-hub>=0.16.0
      - peft>=0.4.0
      - bitsandbytes>=0.41.0
      - python-dotenv>=1.0.0
      - wandb>=0.15.0
      - tensorboard>=2.13.0
    # Note: gensim not included due to Python 3.13 compatibility issues
